# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit_card_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('limit_bal', models.FloatField()),
                ('sex', models.IntegerField()),
                ('education', models.IntegerField()),
                ('marriage', models.IntegerField()),
                ('age', models.IntegerField()),
                ('pay_0', models.IntegerField()),
                ('pay_2', models.IntegerField()),
                ('pay_3', models.IntegerField()),
                ('pay_4', models.IntegerField()),
                ('pay_5', models.IntegerField()),
                ('pay_6', models.IntegerField()),
                ('bill_amt_1', models.FloatField()),
                ('bill_amt_2', models.FloatField()),
                ('bill_amt_3', models.FloatField()),
                ('bill_amt_4', models.FloatField()),
                ('bill_amt_5', models.FloatField()),
                ('bill_amt_6', models.FloatField()),
            ],
        ),
    ]
